HOST: http://insales.ru/

--- insales.ru test API ---

--
Категории на складе
--

Получение списка категорий
GET /admin/categories.xml
< 200
< Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<categories type="array">
    <category>
        <id type="integer">28429</id>
        <parent-id type="integer" nil="true"/>
        <title>Склад</title>
        <position type="integer">1</position>
        <created-at type="timestamp">2009-10-22 19:41:19 +0400</created-at>
        <updated-at type="timestamp">2009-11-05 15:00:11 +0300</updated-at>
    </category>
    <category>
        <id type="integer">32142</id>
        <parent-id type="integer">28429</parent-id>
        <title>Мужская одежда</title>
        <position type="integer">2</position>
        <created-at type="timestamp">2009-11-19 14:06:31 +0300</created-at>
        <updated-at type="timestamp">2009-11-19 14:06:36 +0300</updated-at>
    </category>
    <category>
        <id type="integer">28479</id>
        <parent-id type="integer">28429</parent-id>
        <title>Женская одежда</title>
        <position type="integer">1</position>
        <created-at type="timestamp">2009-10-23 19:47:24 +0400</created-at>
        <updated-at type="timestamp">2009-10-23 19:47:24 +0400</updated-at>
    </category>
    <category>
        <id type="integer">28480</id>
        <parent-id type="integer">28429</parent-id>
        <title>Платья</title>
        <position type="integer">1</position>
        <created-at type="timestamp">2009-10-23 19:47:24 +0400</created-at>
        <updated-at type="timestamp">2009-10-23 19:47:24 +0400</updated-at>
   </category>
</categories>

Получение информации о категории
GET /admin/categories/32142.xml
< 200
< Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<category>
    <id type="integer">32142</id>
    <parent-id type="integer">28429</parent-id>
    <title>Мужская одежда</title>
    <position type="integer">2</position>
    <created-at type="timestamp">2009-11-19 14:06:31 +0300</created-at>
    <updated-at type="timestamp">2009-11-19 14:06:36 +0300</updated-at>
</category>

Добавление новой категории
POST /admin/categories.xml
> Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<category>
    <parent-id type="integer">28429</parent-id>
    <title>Мужская одежда</title>
</category>
< 200
< Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<category>
    <id type="integer">32142</id>
    <parent-id type="integer">28429</parent-id>
    <title>Мужская одежда</title>
    <position type="integer">2</position>
    <created-at type="timestamp">2009-11-19 14:06:31 +0300</created-at>
    <updated-at type="timestamp">2009-11-19 14:06:36 +0300</updated-at>
</category>

Редактирование категории
PUT /admin/categories/32142.xml
> Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<category>
    <id type="integer">32142</id>
    <title>Одежда</title>
</category>
< 200
< Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<category>
    <id type="integer">32142</id>
    <parent-id type="integer">28429</parent-id>
    <title>Одежда</title>
    <position type="integer">2</position>
    <created-at type="timestamp">2009-11-19 14:06:31 +0300</created-at>
    <updated-at type="timestamp">2009-11-19 14:06:36 +0300</updated-at>
</category>

Удаление категории
DELETE /admin/categories/32142.xml
< 200

--
Товары
--

Получение списка товаров
GET /admin/products.xml?category_id=478
< 200
< Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<products type="array">
    <product>
        <category-id type="integer">478</category-id>
        <created-at type="timestamp">2009-06-04 14:22:34 +0400</created-at>
        <id type="integer">41658</id>
        <is-hidden type="boolean">false</is-hidden>
        <updated-at type="timestamp">2010-07-14 13:40:01 +0400</updated-at>
        <title>Van Gogh Ruled Peach Notebook</title>
        <description>&lt;p&gt;&lt;span style=&quot;font-family: 'Times New Roman'; font-size: 16px;&quot;&gt; &lt;/span&gt;&lt;/p&gt;</description>
        <short-description>Алая записная книжка "Ван Гог" в линейку</short-description>
        <permalink>Van-Gogh-Ruled-Rose-Notebook</permalink>
        <html-title nil="true"/>
        <meta-keywords nil="true"/>
        <meta-description nil="true"/>
        <characteristics type="array">
            <characteristic>
                <id type="integer">328</id>
                <position type="integer">1</position>
                <property-id type="integer">106</property-id>
                <title>в линейку</title>
                <permalink>rulled</permalink>
            </characteristic>
        </characteristics>
        <properties type="array">
            <property>
                <id type="integer">106</id>
                <position type="integer">1</position>
                <title>Бумага</title>
                <permalink>bumaga</permalink>
            </property>
        </properties>
        <option-names type="array"/>
        <images type="array">
            <image>
                <created-at type="timestamp">2009-06-04 14:22:34 +0400</created-at>
                <id type="integer">24690</id>
                <position type="integer">1</position>
                <url>http://static.insales.ru/images/products/24690/thumb/vangogh-red.jpg</url>
                <title nil="true"/>
            </image>
        </images>
        <variants type="array">
            <variant>
                <cost-price type="decimal">487.0</cost-price>
                <created-at type="timestamp">2009-06-04 14:22:34 +0400</created-at>
                <id type="integer">48136</id>
                <old-price type="decimal" nil="true"/>
                <price type="decimal">740.0</price>
                <product-id type="integer">41658</product-id>
                <quantity type="integer" nil="true"/>
                <sku>QP021MVEN-r</sku>
                <updated-at type="timestamp">2010-07-16 13:20:04 +0400</updated-at>
                <title nil="true"/>
                <option-values type="array"/>
            </variant>
        </variants>
    </product>
    <product>
        <category-id type="integer">478</category-id>
        <created-at type="timestamp">2009-04-10 00:00:05 +0400</created-at>
        <id type="integer">15757</id>
        <is-hidden type="boolean">false</is-hidden>
        <updated-at type="timestamp">2009-12-08 14:58:34 +0300</updated-at>
        <title>Van Gogh Sketchbook Peach</title>
        <description nil="true" />
        <short-description>Персиковая записная книжка "Ван Гог" для рисунков</short-description>
        <permalink>Van-Gogh-Sketchbook-Peach</permalink>
        <html-title nil="true"/>
        <meta-keywords nil="true"/>
        <meta-description nil="true"/>
        <characteristics type="array">
            <characteristic>
                <id type="integer">328</id>
                <position type="integer">1</position>
                <property-id type="integer">106</property-id>
                <title>в линейку</title>
                <permalink>rulled</permalink>
            </characteristic>
        </characteristics>
        <properties type="array">
            <property>
                <id type="integer">106</id>
                <position type="integer">1</position>
                <title>Бумага</title>
                <permalink>bumaga</permalink>
            </property>
        </properties>
        <option-names type="array"/>
        <images type="array">
            <image>
                <created-at type="timestamp">2009-04-10 00:00:05 +0400</created-at>
                <id type="integer">13886</id>
                <position type="integer">1</position>
                <url>http://static.insales.ru/images/products/13886/thumb/vangogh-orange.jpg</url>
                <title nil="true"/>
            </image>
        </images>
        <variants type="array">
            <variant>
                <cost-price type="decimal">487.0</cost-price>
                <created-at type="timestamp">2009-04-10 00:00:05 +0400</created-at>
                <id type="integer">16638</id>
                <old-price type="decimal" nil="true"/>
                <price type="decimal">740.0</price>
                <product-id type="integer">15757</product-id>
                <quantity type="integer">0</quantity>
                <sku>QP023MVEN-o</sku>
                <updated-at type="timestamp">2010-07-16 13:20:05 +0400</updated-at>
                <title nil="true"/>
                <option-values type="array"/>
            </variant>
        </variants>
    </product>
</products>

Получение информации о товаре
GET /admin/products/41658.xml
< 200
< Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<product>
    <category-id type="integer">478</category-id>
    <created-at type="timestamp">2009-06-04 14:22:34 +0400</created-at>
    <id type="integer">41658</id>
    <is-hidden type="boolean">false</is-hidden>
    <updated-at type="timestamp">2010-07-14 13:40:01 +0400</updated-at>
    <title>Van Gogh Ruled Peach Notebook</title>
    <description>&lt;p&gt;&lt;span style=&quot;font-family: 'Times New Roman'; font-size: 16px;&quot;&gt; &lt;/span&gt;&lt;/p&gt;</description>
    <short-description>Алая записная книжка "Ван Гог" в линейку</short-description>
    <permalink>Van-Gogh-Ruled-Rose-Notebook</permalink>
    <html-title nil="true"/>
    <meta-keywords nil="true"/>
    <meta-description nil="true"/>
    <characteristics type="array">
        <characteristic>
            <id type="integer">328</id>
            <position type="integer">1</position>
            <property-id type="integer">106</property-id>
            <title>в линейку</title>
            <permalink>rulled</permalink>
        </characteristic>
    </characteristics>
    <properties type="array">
        <property>
            <id type="integer">106</id>
            <position type="integer">1</position>
            <title>Бумага</title>
            <permalink>bumaga</permalink>
        </property>
    </properties>
    <option-names type="array"/>
    <images type="array">
        <image>
            <created-at type="timestamp">2009-06-04 14:22:34 +0400</created-at>
            <id type="integer">24690</id>
            <position type="integer">1</position>
            <url>http://static.insales.ru/images/products/24690/thumb/vangogh-red.jpg</url>
            <title nil="true"/>
        </image>
    </images>
    <variants type="array">
        <variant>
            <cost-price type="decimal">487.0</cost-price>
            <created-at type="timestamp">2009-06-04 14:22:34 +0400</created-at>
            <id type="integer">48136</id>
            <old-price type="decimal" nil="true"/>
            <price type="decimal">740.0</price>
            <product-id type="integer">41658</product-id>
            <quantity type="integer" nil="true"/>
            <sku>QP021MVEN-r</sku>
            <updated-at type="timestamp">2010-07-16 13:20:04 +0400</updated-at>
            <title nil="true"/>
            <option-values type="array"/>
        </variant>
    </variants>
</product>

--
Добавление товара
--

Добавление товара с параметрами
POST /admin/products.xml
> Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<product>
    <category-id type="integer">478</category-id>
    <title>Van Gogh Ruled Peach Notebook</title>
    <description>&lt;p&gt;&lt;span style=&quot;font-family: 'Times New Roman'; font-size: 16px;&quot;&gt; &lt;/span&gt;&lt;/p&gt;</description>
    <short-description>Алая записная книжка "Ван Гог" в линейку</short-description>
    <properties-attributes type="array">
        <properties-attribute>
            <title>Бумага</title>
            <value>в линейку</value>
        </properties-attribute>
    </properties-attributes>
    <variants-attributes type="array">
        <variant>
            <sku>QP021MVEN-r</sku>
            <quantity type="integer" nil="true"/>
            <price type="decimal">740.0</price>
            <cost-price type="decimal">487.0</cost-price>
            <old-price type="decimal" nil="true"/>
        </variant>
    </variants-attributes>
</product>
< 200
< Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<product>
    <category-id type="integer">478</category-id>
    <created-at type="timestamp">2009-06-04 14:22:34 +0400</created-at>
    <id type="integer">41658</id>
    <is-hidden type="boolean">false</is-hidden>
    <updated-at type="timestamp">2010-07-14 13:40:01 +0400</updated-at>
    <title>Van Gogh Ruled Peach Notebook</title>
    <description>&lt;p&gt;&lt;span style=&quot;font-family: 'Times New Roman'; font-size: 16px;&quot;&gt; &lt;/span&gt;&lt;/p&gt;</description>
    <short-description>Алая записная книжка "Ван Гог" в линейку</short-description>
    <permalink>Van-Gogh-Ruled-Rose-Notebook</permalink>
    <html-title nil="true"/>
    <meta-keywords nil="true"/>
    <meta-description nil="true"/>
    <characteristics type="array">
        <characteristic>
            <id type="integer">328</id>
            <position type="integer">1</position>
            <property-id type="integer">106</property-id>
            <title>в линейку</title>
            <permalink>rulled</permalink>
        </characteristic>
    </characteristics>
    <properties type="array">
        <property>
            <id type="integer">106</id>
            <position type="integer">1</position>
            <title>Бумага</title>
            <permalink>bumaga</permalink>
        </property>
    </properties>
    <option-names type="array"/>
    <images type="array" />
    <variants type="array">
        <variant>
            <cost-price type="decimal">487.0</cost-price>
            <created-at type="timestamp">2009-06-04 14:22:34 +0400</created-at>
            <id type="integer">48136</id>
            <old-price type="decimal" nil="true"/>
            <price type="decimal">740.0</price>
            <product-id type="integer">41658</product-id>
            <quantity type="integer" nil="true"/>
            <sku>QP021MVEN-r</sku>
            <updated-at type="timestamp">2010-07-16 13:20:04 +0400</updated-at>
            <title nil="true"/>
            <option-values type="array"/>
        </variant>
    </variants>
</product>

Добавление товара со свойствами
POST /admin/products.xml
> Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<product>
    <category-id type="integer">478</category-id>
    <is-hidden type="boolean">false</is-hidden>
    <title>Модная майка</title>
    <options type="array">
        <option>
            <title>Размер</title>
            <value>XL</value>
        </option>
        <option>
            <title>Цвет</title>
            <value>белый</value>
        </option>
    </options>
    <variants-attributes type="array">
        <variant>
            <cost-price type="decimal">487.0</cost-price>
            <old-price type="decimal">1000</old-price>
            <price type="decimal">740.0</price>
            <quantity type="integer">10</quantity>
        </variant>
    </variants-attributes>
</product>
< 200
< Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<product>
    <id type="integer">41658</id>
    <category-id type="integer">478</category-id>
    <created-at type="timestamp">2009-06-04 14:22:34 +0400</created-at>
    <is-hidden type="boolean">false</is-hidden>
    <updated-at type="timestamp">2010-07-14 13:40:01 +0400</updated-at>
    <title>Майка</title>
    <description nil="true">
    <short-description nil="true">
    <permalink>Majka</permalink>
    <html-title nil="true"/>
    <meta-keywords nil="true"/>
    <meta-description nil="true"/>
    <characteristics type="array"/>
    <properties type="array"/>
    <option-names type="array">
        <option-name>
            <id type="integer">1171</id>
            <position type="integer">1</position>
            <title>Размер</title>
        </option-name>
        <option-name>
            <id type="integer">1172</id>
            <position type="integer">2</position>
            <title>Цвет</title>
        </option-name>
    </option-names>
    <images type="array" />
    <variants type="array">
        <variant>
            <id type="integer">48136</id>
            <product-id type="integer">41658</product-id>
            <cost-price type="decimal">487.0</cost-price>
            <old-price type="decimal">1000</old-price>
            <price type="decimal">740.0</price>
            <quantity type="integer">10</quantity>
            <sku nil="true" />
            <title>XL/белый</title>
            <created-at type="timestamp">2009-06-04 14:22:34 +0400</created-at>
            <updated-at type="timestamp">2010-07-16 13:20:04 +0400</updated-at>
            <option-values type="array">
                <option-value>
                    <id type="integer">5649</id>
                    <option-name-id type="integer">1171</option-name-id>
                    <position type="integer">1</position>
                    <value>XL</value>
                </option-value>
                <option-value>
                    <id type="integer">5650</id>
                    <option-name-id type="integer">1172</option-name-id>
                    <position type="integer">1</position>
                    <value>белый</value>
                </option-value>
            </option-values>
        </variant>
    </variants>
</product>

Добавление товара с несколькими модификациями
PUT /admin/products/478.xml
> Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<product>
    <id type="integer">478</category-id>
    <variants-attributes type="array">
        <variant>
            <cost-price type="decimal">487.0</cost-price>
            <old-price type="decimal">1000</old-price>
            <price type="decimal">740.0</price>
            <quantity type="integer">10</quantity>
            <options>
                <option> 
                    <option-name-id type="integer">202088</option-name-id> 
                    <value>value 1</value> 
                </option> 
            </options>
        </variant>
        <variant>
            <cost-price type="decimal">600.0</cost-price>
            <old-price type="decimal">1100</old-price>
            <price type="decimal">800.0</price>
            <quantity type="integer">2</quantity>
            <options>
                <option> 
                    <option-name-id type="integer">202088</option-name-id> 
                    <value>value 2</value> 
                </option> 
            </options>
        </variant>
    </variants-attributes>
</product>
< 200

--
Редактирование товара
--

Изменение наименования товара
PUT /admin/products/41658.xml
> Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<product>
    <id type="integer">41658</id>
    <title>Van Gogh Ruled Peach Notebook</title>
</product>
< 200

Изменение параметров товара
PUT /admin/products/41658.xml
> Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<product>
    <id type="integer">41658</id>
    <properties-attributes type="array">
        <properties-attribute>
            <title>Бумага</title>
            <value>в линейку</value>
        </properties-attribute>
    </properties-attributes>
</product>
< 200

Удаление товара
DELETE /admin/products/41658.xml
< 200

--
Изображения товара
--

Получение всех изображений
GET /admin/products/2336153/images.xml
< 200
< Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<images type="array">
    <image>
        <id type="integer">1489191</id>
        <product-id type="integer">2336153</product-id>
        <position type="integer">1</position>
        <original-url>http://static.insales.ru/images/products/1/6439/1489191/yhst-71326348041790_2147_5697670.jpg</original-url>
        <title nil="true"/>
        <created-at type="timestamp">2011-04-04 15:48:33 +0400</created-at>
    </image>
    <image>
        <id type="integer">1489187</id>
        <product-id type="integer">2336153</product-id>
        <position type="integer">2</position>
        <original-url>http://static.insales.ru/images/products/1/6435/1489187/yhst-71326348041790_2147_5571401.jpg</original-url>
        <title nil="true"/>
        <created-at type="timestamp">2011-04-04 15:48:27 +0400</created-at>
    </image>
</images>

Получение изображения
GET /admin/products/2336153/images/1489191.xml
< 200
< Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<image>
    <id type="integer">1489191</id>
    <product-id type="integer">2336153</product-id>
    <position type="integer">1</position>
    <original-url>http://static.insales.ru/images/products/1/6439/1489191/yhst-71326348041790_2147_5697670.jpg</original-url>
    <title nil="true"/>
    <created-at type="timestamp">2011-04-04 15:48:33 +0400</created-at>
</image>

--
Добавление изображения
--

Добавлении изображения выложенного в интернет
POST /admin/products/2336153/images.xml
> Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<image>
    <title>ImageTile</title>
    <filename>myimage.jpg</filename>
    <src>http://some-hosting.ru/some_image.jpg</src>
</image>
< 200
< Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<image>
    <id type="integer">1489191</id>
    <product-id type="integer">2336153</product-id>
    <position type="integer">1</position>
    <original-url>http://static.insales.ru/images/products/1/6439/1489191/some_image.jpg</original-url>
    <title>ImageTile</title>
    <created-at type="timestamp">2011-04-04 15:48:33 +0400</created-at>
</image>

Передача изображения в теле запроса
POST /admin/products/2336153/images.xml
> Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<image>
    <title>ImageTile</title>
    <filename>myimage.jpg</filename>
    <attachment>
/9j/4AAQSkZJRgABAQEAAQABAAD/2wBDAAkGBwgHBgkIBwgKCgkLDRYPDQwMDRsUFRAWIB0i
IiAdHx8kKDQsJCYxJx8fLT0tMTU3Ojo6Iys/RD84QzQ5Ojf/2wBDAQoKCg0MDRoPDxo3JR8l
Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzf/wAAR
CABrAJYDAREAAhEBAxEB/8QAHAABAAMBAQEBAQAAAAAAAAAAAAEGBwUEAgMI/8QAPBAAAAUD
AgQDBAcGBwAAAAAAAAECAwQFBhEHEiExQVETYXEUgZHBIiMyN1KhsQgVFzRidRYzQlR0lOH/
xAAaAQEAAwEBAQAAAAAAAAAAAAAAAwQFBgIB/8QAJhEBAAICAQQDAAEFAAAAAAAAAAECAwQR
BRIhMQYTIlEUMkGBsf/aAAwDAQACEQMRAD8A3EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAEAAAAD4JH0AAAAAAAAAAAAAEZAMgGQDID4cWlCFLWokpSWTMzwR
EPkzEe32ImZ4iFGreplNhuKZprapziTwayPa2R+vUVcm3WniPLoNL49n2I7sn5hw2NS6ut0j
XFieGZ/ZIlEePXIhnctEc8NK3xnFEeLzy0WgVdqs05uW0W1R8HEZ4oV2FvFljLXlyu3rW1ss
0s6eRMrGQDIBkAyAZAMgGQDIBkAyAgAAAABlep9bqFTrDVp0RLji1ESpJN81GfEkmfQiLiYq
Z5taeyG70vFixV/qMvqPT7oulWGUKq04yWZcWo5cC95iOunEzzZfz/JrRHbhr/t2y01oySIm
35ZK7+IR/ISzqY5jhRn5Btz74Wum0+NTIiI0Nom20/Ez7n3MT0pWkcVY+fPkzX77zzMvWPaE
AAAAAAAAAAAAAZpe8yUzqtZ0dmS82y6S/EbQ4ZJXz5l1AaWAAACn2hTGokuu16aRE/Jlul4i
v9DKDwRfl+gjiOObSuZslr1pij/CgV++q7clV9gt9TzEda9jLbPBx3zM+nyFS+a97cVb+v03
Br4vsz+0u2ffkZj2pMmQpaS3G23LM1l8jD6s0eSN7QvPbP8Ax09P7/nqqbVJrzhupdV4bTyy
wtC+iVd+w94c8zPbZB1HpeOMf24Wti45sAAGc6u1ao0yXbCafNfjFIqJIeJpWN6clwPuQDRj
5gAAAAAAAAMuvz73rJ9F/MBcLruyNbL1LblR3XTqMoo6DbMiJBn1PPTiAr1S1SjfvF6DblFq
FdcYUaXHYqfqyPsSsHkAoeqtOmVVulVunTKJNcMibTMThKjPpnhj3lgBbbhhrft2pRYacOux
3CQRdVGRjzeJ7ZT694jNW1vXLDtO6xFoFztSKkRoZNCmVLMv8sz6/lgZ+G8Uv+nX9SwW2Nbj
G3+HLjTWEvxHm3mlFlK21EZGNGLRPlxl8dqW4tHCvvWHbz1TVUVw1lJU7425LqiLdnOceojn
FTnuW46jsVx/XFvDv1CbGpsJ6ZOeQxGYRvccXySRCVRZ/wDxaZlmtdDtmt1KOk8e0NMYQfpz
AdK1tS6PXqmVJfjy6ZUz+zGmo2ms+xH38jAcLW3+dtD+6F+qQGqdQFLurUiiW7O/dxJkVCpc
jiQ0b1JPsZ9D8uYDlRdXqYiU0xXaPVaOl08JelM/Q9/UBorbrbrKXm3EqaUnclaVZSZc857A
M/l6rwFz3odv0ep1tTKtq3IbWWyPyMB+tF1SpkyrtUqrU6oUaY8ZJaTNbwlZnyLPQBfgGXX5
971k+i/mA8v7QUdUuLbsZCtq3pxtpV2MyIsgNKoFFhUCkx6bTWUtMMpIuBcVH1UZ9TMBUta6
RFqNizpTrSfaIJJeZdx9JPEiMs9jIBYrHmOz7Qo0uQrc67DbNau545h5PDiXZpxTK68uXEWc
GYvipSE5Qs+5p7+ZCDLgrb01dPquXXr2281Z9Nty7bKcVMhuOeAk8m9FUak4/qT/AOCtOPJj
/tbVNvT3qxS8eVvsfUoqpJap1bQhuS4e1qQjghZ9jLoYmxbHd+be2bv9J+mJyYvMfwudz0Kn
3FSXIFX3+xmoluEhzZ9njxPsLTCVxWoljUBpumtVdlLcdJNpRHbUtKSLhzSWDAZ9qfeNs3BK
oU235ZuVSJNTlwmFIPw855mRZ4kXxAWfWzjLs8+9TT+qQF7vGrKoVsVSpox4keOpTefxYwn8
wFH0VpdPhW8Vcmvx11apLW64864W9KcnguPLPM/UBcrph0i4aHLps1+K4h1tRIM3E5QvHBRe
ZGAz7TSXUKvpJWaWwta5kNL0aPg+JkackRfEyAenRe5reiWtHo7spiDU2XFlIZkH4anFGo+O
T58MFjyAXi5bZo13RY6Km2byGHPEZdZcwpJ+Si6AO6lOxJJLJ4Ii48wGX35971k+i/mAjW/+
YtP+6p/UgGp9QFS1X+7yuf8AG+ZAPHb1VXRNJ6XUm43tJsQWlG1u25LgR8R4vbsjlPrYYz5Y
pzxy/Syb+Zuec/DciFEdQgltl4u7xC69OgjxZu+eF3e6ZbVpF4nmFyWSVJMlERkZcSMuGBN4
ZkTMS/nC5W4zV3zEUfHhJlF4Ph8iVkuXvGZfj7fDudWZnUi2T3w0PWabLVCoFAZfUwisS0tS
HEng9hbSMvTKs+4ajh7cczwulItShUeC3Eg0uKltssblNEpSj7qM+JmDyz3XWPBiU6hNx48d
l1yopP6tskmZEXHl6kA9Gt2EvWi4rghNSTuUfIvsgLbqZDcn2HW2GSM1nGNZEXXb9L5AM801
05tG5rPhVKUxIXKVuQ/skKSRLI+xcuGD94C0fwYsz/aS/wDtKAWS1bUpFoxX2KO2400+slue
I4asmRY6gPxr1i2zcLinqlSWHHlc3m8oWfmZpxkBnl22bM09p67is2sTWWoq0m/Cfc3IUkzx
7+fI/iA1a3qmVZoUCpkjZ7Uwh00fhMy4l8QFVuy3KnUdRLYrESOlcKASvaHDWRGnPlzMA1Qt
uqXC9b6qWylwoc8nnzUsk7U5Ljx5gL51AV6/qXLrNn1SnU9BOSZDO1tJqIiM8l1MBNq0dyJZ
lOpFVZTvbhpYfbzuLlgyyPkxEx5eqXms90M1remlbpc85NvLVIaSrc0aHNjrfl5+opW17RPN
HUa/V8GXH2bDzvQdRag17I6VQNsywZG4SSMvM+o+cZvUvcZOmY/1HCx2Ppo5T5rVSrq21OtH
uajIPJJV0NR9TLsJMWvNZ7rKG/1eMtZx4vEfy72pdnKu6jtIhvlHqUNzxorquW7qRn0zw49y
IW2Cr0S6NSKeymHULNTPkILb7U1IJKXPM8ZL9AHCuqzL4upUSs1ZpkpbUhCWKaw4kksM81KN
RnxPJF3+QDSr7tRm77eXTXXfAeSonY72M+G4RcD9OZAPPYrN1sxZUG8CiPpZJKI8lo8m8nBk
e78uhcwFVVaV1WPV5UyxSYnUqUve5TH1YNB/0mZ/A8/EB6/8Uakyy8KNZMeM4ZY8WRJI0kff
GSAWSoUCdcVjLpFwPtpqMhj611j7KHSPJGXkR4AUyjVHUe04LVKlW03WmIxbGZLMgiM0FyI+
p/AB8VqJfuoTTdLnUpmgUhSyVIUt0luLIjzjufpggGqUyEzTafGgxU7WYzSWkEf4UlggHrwA
YAAAAARgAwAkAARgAwAkAwAYARgBICMAGAEgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAgBIAAAAAAAAAAAAAAAAAAAAAAgB//2Q==
    </attachment>
</image>
< 200
< Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<image>
    <id type="integer">1489191</id>
    <product-id type="integer">2336153</product-id>
    <position type="integer">1</position>
    <original-url>http://static.insales.ru/images/products/1/6439/1489191/myimage.jpg</original-url>
    <title>ImageTile</title>
    <created-at type="timestamp">2011-04-04 15:48:33 +0400</created-at>
</image>

Изменение изображения
PUT /admin/products/2336153/images/1489191.xml
> Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<image>
    <position type="integer">5</position>
    <title>Other ImageTile</title>
</image>
< 200

Удаление изображения
DELETE /admin/products/2336153/images/1489191.xml
< 200

--
Модификации товара
--

Получение всех модификаций товара
GET /admin/products/1157664/variants.xml
< 200
< Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<variants type="array">
    <variant>
        <id type="integer">1157664</id>
        <product-id type="integer">182183</product-id>
        <cost-price type="decimal" nil="true"/>
        <old-price type="decimal" nil="true"/>
        <price type="decimal">440.0</price>
        <quantity type="integer" nil="true"/>
        <sku nil="true"/>
        <created-at type="timestamp">2010-07-03 20:04:28 +0400</created-at>
        <updated-at type="timestamp">2010-07-03 20:04:28 +0400</updated-at>
        <option-values type="array">
            <option-value>
                <id type="integer">8093</id>
                <option-name-id type="integer">1576</option-name-id>
                <position type="integer">3</position>
                <title>Черный</title>
            </option-value>
            <option-value>
                <id type="integer">8092</id>
                <option-name-id type="integer">1575</option-name-id>
                <position type="integer">24</position>
                <title>96</title>
            </option-value>
        </option-values>
    </variant>
    <variant>
        <id type="integer">1157665</id>
        <product-id type="integer">182183</product-id>
        <cost-price type="decimal" nil="true"/>
        <old-price type="decimal" nil="true"/>
        <price type="decimal">440.0</price>
        <quantity type="integer" nil="true"/>
        <sku nil="true"/>
        <created-at type="timestamp">2010-07-03 20:04:39 +0400</created-at>
        <updated-at type="timestamp">2010-07-03 20:04:39 +0400</updated-at>
        <option-values type="array">
            <option-value>
                <id type="integer">7941</id>
                <option-name-id type="integer">1576</option-name-id>
                <position type="integer">2</position>
                <title>Белый</title>
            </option-value>
            <option-value>
                <id type="integer">8094</id>
                <option-name-id type="integer">1575</option-name-id>
                <position type="integer">25</position>
                <title>100</title>
            </option-value>
        </option-values>
    </variant>
    <variant>
        <id type="integer">1157666</id>
        <product-id type="integer">182183</product-id>
        <cost-price type="decimal" nil="true"/>
        <old-price type="decimal" nil="true"/>
        <price type="decimal">440.0</price>
        <quantity type="integer" nil="true"/>
        <sku nil="true"/>
        <created-at type="timestamp">2010-07-03 20:04:39 +0400</created-at>
        <updated-at type="timestamp">2010-07-03 20:04:39 +0400</updated-at>
        <option-values type="array">
            <option-value>
                <id type="integer">8093</id>
                <option-name-id type="integer">1576</option-name-id>
                <position type="integer">3</position>
                <title>Черный</title>
            </option-value>
            <option-value>
                <id type="integer">8094</id>
                <option-name-id type="integer">1575</option-name-id>
                <position type="integer">25</position>
                <title>100</title>
            </option-value>
        </option-values>
    </variant>
</variants>

Получение модификации
GET /admin/products/182183/variants/1157664.xml
< 200
< Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<variant>
    <id type="integer">1157664</id>
    <product-id type="integer">182183</product-id>
    <cost-price type="decimal" nil="true"/>
    <old-price type="decimal" nil="true"/>
    <price type="decimal">440.0</price>
    <quantity type="integer" nil="true"/>
    <sku nil="true"/>
    <created-at type="timestamp">2010-07-03 20:04:28 +0400</created-at>
    <updated-at type="timestamp">2010-07-03 20:04:28 +0400</updated-at>
    <option-values type="array">
        <option-value>
            <id type="integer">8093</id>
            <option-name-id type="integer">1576</option-name-id>
            <position type="integer">3</position>
            <title>Черный</title>
        </option-value>
        <option-value>
            <id type="integer">8092</id>
            <option-name-id type="integer">1575</option-name-id>
            <position type="integer">24</position>
            <title>96</title>
        </option-value>
    </option-values>
</variant>

Добавление модификации
POST /admin/products/182183/variants.xml
> Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<variant>
    <price type="decimal">440.0</price>
    <options type="array">
        <option>
            <option-name-id type="integer">1576</option-name-id>
            <value>Черный</value>
        </option>
        <option>
            <option-name-id type="integer">1575</option-name-id>
            <value>96</value>
        </option>
    </options>
</variant>
< 200
< Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<variant>
    <id type="integer">1157664</id>
    <product-id type="integer">182183</product-id>
    <cost-price type="decimal" nil="true"/>
    <old-price type="decimal" nil="true"/>
    <price type="decimal">440.0</price>
    <quantity type="integer" nil="true"/>
    <sku nil="true"/>
    <created-at type="timestamp">2010-07-03 20:04:28 +0400</created-at>
    <updated-at type="timestamp">2010-07-03 20:04:28 +0400</updated-at>
    <option-values type="array">
        <option-value>
            <id type="integer">8093</id>
            <option-name-id type="integer">1576</option-name-id>
            <position type="integer">3</position>
            <title>Черный</title>
        </option-value>
        <option-value>
            <id type="integer">8092</id>
            <option-name-id type="integer">1575</option-name-id>
            <position type="integer">24</position>
            <title>96</title>
        </option-value>
    </option-values>
</variant>

Изменение модификации
PUT /admin/products/182183/variants/1157664.xml
> Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<variant>
    <id type="integer">1157664</id>
    <price type="decimal">440.0</price>
</variant>
< 200
< Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<variant>
    <id type="integer">1157664</id>
    <product-id type="integer">182183</product-id>
    <cost-price type="decimal" nil="true"/>
    <old-price type="decimal" nil="true"/>
    <price type="decimal">440.0</price>
    <quantity type="integer" nil="true"/>
    <sku nil="true"/>
    <created-at type="timestamp">2010-07-03 20:04:28 +0400</created-at>
    <updated-at type="timestamp">2010-07-03 20:04:28 +0400</updated-at>
    <option-values type="array">
        <option-value>
            <id type="integer">8093</id>
            <option-name-id type="integer">1576</option-name-id>
            <position type="integer">3</position>
            <title>Черный</title>
        </option-value>
        <option-value>
            <id type="integer">8092</id>
            <option-name-id type="integer">1575</option-name-id>
            <position type="integer">24</position>
            <title>96</title>
        </option-value>
    </option-values>
</variant>

Удаление модификации
DELETE /admin/products/182183/variants/1157664.xml
< 200

Групповое обновление модификаций
PUT /admin/products/variants_group_update.xml
> Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<variants type="array">
  <variant>
    <id type="integer">1</id>
    <price type="decimal">110.0</price>
    <quantity type="integer">2</quantity>
  </variant>
  <variant>
    <id type="integer">2</id>
    <price type="decimal">200.0</price>
    <quantity type="integer">3</quantity>
  </variant> 
</variants>
< 200
< Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<objects type="array">
  <object>
    <id type="integer">1</id>
    <status>ok</status>
  </object>
  <object>
    <id type="integer">2</id>
    <status>ok</status>
  </object>
</objects>

--
Свойства товара
--

Получение списка свойств
GET /admin/option_names.xml
< 200
< Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<option-names type="array">
    <option-name>
        <id type="integer">1093</id>
        <title>Модификация</title>
        <position type="integer">1</position>
    </option-name>
    <option-name>
        <id type="integer">1575</id>
        <title>Размер</title>
        <position type="integer">2</position>
    </option-name>
    <option-name>
        <id type="integer">1576</id>
        <title>Цвет</title>
        <position type="integer">3</position>
    </option-name>
    <option-name>
        <id type="integer">1786</id>
        <title>Чашечка</title>
        <position type="integer">4</position>
    </option-name>
    <option-name>
        <id type="integer">4331</id>
        <title>Ден</title>
        <position type="integer">5</position>
    </option-name>
    <option-name>
        <id type="integer">10091</id>
        <title>Рост</title>
        <position type="integer">6</position>
    </option-name>
</option-names>

Получение информации о свойстве
GET /admin/option_names/1575.xml
< 200
< Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<option-name>
    <id type="integer">1575</id>
    <title>Размер</title>
    <position type="integer">2</position>
</option-name>

Добавление свойства
POST /admin/option_names.xml
> Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<option-name>
    <title>Размер</title>
</option-name>
< 200
< Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<option-name>
    <id type="integer">1575</id>
    <title>Размер</title>
    <position type="integer">2</position>
</option-name>

Изменение свойства
PUT /admin/option_names/1575.xml
> Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<option-name>
    <position type="integer">7</position>
</option-name>
< 200
< Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<option-name>
    <id type="integer">1575</id>
    <title>Размер</title>
    <position type="integer">7</position>
</option-name>

Удаление свойства
DELETE /admin/option_names/1575.xml
< 200

--
Значения свойств
--

--
Получение списка значений свойств
--

Вывод значений для всех свойств
GET /admin/option_values.xml
< 200
< Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<option-values type="array">
    <option-value>
        <id type="integer">7942</id>
        <option-name-id type="integer">1576</option-name-id>
        <position type="integer">1</position>
        <title>Бежевый</title>
    </option-value>
    <option-value>
        <id type="integer">7941</id>
        <option-name-id type="integer">1576</option-name-id>
        <position type="integer">2</position>
        <title>Белый</title>
    </option-value>
    <option-value>
        <id type="integer">8093</id>
        <option-name-id type="integer">1576</option-name-id>
        <position type="integer">3</position>
        <title>Чёрный</title>
    </option-value>
    <option-value>
        <id type="integer">24987</id>
        <option-name-id type="integer">1575</option-name-id>
        <position type="integer">2</position>
        <title>40</title>
    </option-value>
    <option-value>
        <id type="integer">7452</id>
        <option-name-id type="integer">1575</option-name-id>
        <position type="integer">3</position>
        <title>42</title>
    </option-value>
</option-values>

Вывод значения для определённого свойства
GET /admin/option_names/1576/option_values.xml
< 200
< Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<option-values type="array">
    <option-value>
        <id type="integer">7942</id>
        <option-name-id type="integer">1576</option-name-id>
        <position type="integer">1</position>
        <title>Бежевый</title>
    </option-value>
    <option-value>
        <id type="integer">7941</id>
        <option-name-id type="integer">1576</option-name-id>
        <position type="integer">2</position>
        <title>Белый</title>
    </option-value>
    <option-value>
        <id type="integer">8093</id>
        <option-name-id type="integer">1576</option-name-id>
        <position type="integer">3</position>
        <title>Чёрный</title>
    </option-value>
</option-values>

Получение информации о значении свойства
GET /admin/option_names/1576/option_values/7942.xml
< 200
< Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<option-value>
    <id type="integer">7942</id>
    <option-name-id type="integer">1576</option-name-id>
    <position type="integer">1</position>
    <title>Бежевый</title>
</option-value>

Добавление значения свойства
POST /admin/option_names/1576/option_values.xml
> Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<option-value>
    <title>Бежевый</title>
</option-value>
< 200
< Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<option-value>
    <id type="integer">7942</id>
    <option-name-id type="integer">1576</option-name-id>
    <position type="integer">1</position>
    <title>Бежевый</title>
</option-value>

Изменение значения свойства
PUT /admin/option_names/1576/option_values/7942.xml
> Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<option-value>
    <position type="integer">7</position>
</option-value>
< 200
< Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<option-value>
    <id type="integer">7942</id>
    <option-name-id type="integer">1576</option-name-id>
    <position type="integer">7</position>
    <title>Бежевый</title>
</option-value>

Удаление значения свойства
DELETE /admin/option_names/1576/option_values/7942.xml
< 200

--
Дополнительные поля товара
--

Получение списка дополнительных полей
GET /admin/product_fields.xml
< 200
< Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<objects type="array">
  <product-field>
    <application-id type="integer" nil="true"/>
    <handle>color</handle>
    <id type="integer">3</id>
    <is-hidden type="boolean">false</is-hidden>
    <position type="integer">1</position>
    <title>Цвет</title>
    <type>ProductField::TextArea</type>
  </product-field>
  <product-field>
    <application-id type="integer" nil="true"/>
    <handle>description</handle>
    <id type="integer">8</id>
    <is-hidden type="boolean">false</is-hidden>
    <position type="integer" nil="true"/>
    <title>доп. описание</title>
    <type>ProductField::TextField</type>
  </product-field>
</objects>

Получение информации о дополнительном поле
GET /admin/product_fields/8.xml
< 200
< Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<product-field>
  <application-id type="integer" nil="true"/>
  <handle>description</handle>
  <id type="integer">8</id>
  <is-hidden type="boolean">false</is-hidden>
  <position type="integer" nil="true"/>
  <title>доп. описание</title>
  <type>ProductField::TextField</type>
</product-field>

Добавление дополнительного поля
POST /admin/product_fields.xml
> Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<product-field>
  <title>Размер</title>
  <handle>size</handle>
  <type>ProductField::TextField</type>
</product-field>
< 200
< Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<product-field>
  <application-id type="integer">2</application-id>
  <handle>size</handle>
  <id type="integer">9</id>
  <is-hidden type="boolean" nil="true"/>
  <position type="integer" nil="true"/>
  <title>Размер</title>
  <type>ProductField::TextField</type>
</product-field>

Изменение дополнительного поля
PUT /admin/product_fields/9.xml
> Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<product-field>
  <position>2</position>
</product-field>
< 200
< Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<product-field>
  <application-id type="integer">2</application-id>
  <handle>size</handle>
  <id type="integer">9</id>
  <is-hidden type="boolean" nil="true"/>
  <position type="integer">2</position>
  <title>Размер</title>
  <type>ProductField::TextField</type>
</product-field>

Удаление дополнительного поля
DELETE /admin/product_fields/9.xml
< 200

--
Значения дополнительных полей товара
--

Получение списка значений дополнительных полей товара
GET /admin/products/1/product_field_values.xml
< 200
< Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<product-field-values type="array">
  <product-field-value>
    <id type="integer">851</id>
    <product-field-id type="integer">9</product-field-id>
    <value>three</value>
  </product-field-value>
  <product-field-value>
    <id type="integer">850</id>
    <product-field-id type="integer">8</product-field-id>
    <value>two</value>
  </product-field-value>
</product-field-values>

Получение информации о значении дополнительного поля товара
GET /admin/products/1/product_field_values/9.xml
< 200
< Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
  <product-field-value>
    <id type="integer">851</id>
    <product-field-id type="integer">9</product-field-id>
    <value>three</value>
  </product-field-value>

Добавление значения дополнительного поля товара
POST /admin/products/1/product_field_values.xml
> Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<product-field-value>
  <product-field-id>8</product-field-id>
  <value>seek and destroy</value>
</product-field-value>
< 200
< Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<product-field-value>
  <id type="integer">853</id>
  <product-field-id type="integer">8</product-field-id>
  <value>seek and destroy</value>
</product-field-value>

Изменение значения дополнительного поля товара
PUT /admin/products/1/product_field_values/8.xml
> Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<product-field-value>
  <value>updated value</value>
</product-field-value>
< 200
< Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<product-field-value>
  <id type="integer">853</id>
  <product-field-id type="integer">8</product-field-id>
  <value>updated value</value>
</product-field-value>

Удаление значения дополнительного поля товара
DELETE /admin/products/1/product_field_values/8.xml
< 200

--
Сопутствующие товары
--

Получение списка сопутствующих товаров
GET /admin/products/1/supplementaries.xml
< 200
< Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<products type="array">
  <product>
    <id type="integer">83983</id>
  </product>
  <product>
    <id type="integer">23423</id>
  </product>
</products>

Добавление сопутствующего товара
POST /admin/products/1/supplementaries.xml
> Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<supplementary_ids>87987</supplementary_ids>
< 200

Удаление сопутствующего товара
DELETE /admin/products/1/supplementaries/87987.xml
< 200

--
Аналогичные товары
--

Получение списка аналогичных товаров
GET /admin/products/1/similars.xml
< 200
< Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<products type="array">
  <product>
    <id type="integer">83983</id>
  </product>
  <product>
    <id type="integer">23423</id>
  </product>
</products>

Добавление аналогичного товара
POST /admin/products/1/similars.xml
> Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<similar_ids>87987</similar_ids>
< 200

Удаление аналогичного товара
DELETE /admin/products/1/similars/87987.xml
< 200

--
Категории на сайте
--

Получение списка категорий
GET /admin/collections.xml
< 200
< Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<collections type="array">
    <collection>
        <id type="integer">119233</id>
        <is-hidden type="boolean">false</is-hidden>
        <parent-id type="integer">2628</parent-id>
        <to-torg-mail type="boolean">false</to-torg-mail>
        <to-yandex-market type="boolean">true</to-yandex-market>
        <title>Ежедневники  Moleskine 2011</title>
        <description nil="true"></description>
        <html-title nil="true"></html-title>
        <meta-description nil="true"></meta-description>
        <meta-keywords nil="true"></meta-keywords>
        <permalink>Ежедневники-Moleskine-2011</permalink>
        <url>/collection/Ежедневники-Moleskine-2011</url>
    </collection>
    <collection>
        <id type="integer">72</id>
        <is-hidden type="boolean">false</is-hidden>
        <parent-id type="integer">2628</parent-id>
        <to-torg-mail type="boolean" nil="true"></to-torg-mail>
        <to-yandex-market type="boolean">true</to-yandex-market>
        <title>Moleskine Reporter</title>
        <description nil="true"></description>
        <html-title nil="true"></html-title>
        <meta-description>Moleskine Reporter</meta-description>
        <meta-keywords>Moleskine Reporter</meta-keywords>
        <permalink>moleskine-reporter</permalink>
        <url>/collection/moleskine-reporter</url>
    </collection>
    <collection>
        <id type="integer">12149</id>
        <is-hidden type="boolean">true</is-hidden>
        <parent-id type="integer">2628</parent-id>
        <to-torg-mail type="boolean" nil="true"></to-torg-mail>
        <to-yandex-market type="boolean">true</to-yandex-market>
        <title>Artistic Collection</title>
        <description nil="true"></description>
        <html-title nil="true"></html-title>
        <meta-description nil="true"></meta-description>
        <meta-keywords nil="true"></meta-keywords>
        <permalink>moleskine-artistic-collection</permalink>
        <url>/collection/moleskine-artistic-collection</url>
    </collection>
    <collection>
        <id type="integer">7830</id>
        <is-hidden type="boolean">false</is-hidden>
        <parent-id type="integer">2628</parent-id>
        <to-torg-mail type="boolean" nil="true"></to-torg-mail>
        <to-yandex-market type="boolean">true</to-yandex-market>
        <title>Moleskine XLarge 19х25</title>
        <description nil="true"></description>
        <html-title nil="true"></html-title>
        <meta-description nil="true"></meta-description>
        <meta-keywords nil="true"></meta-keywords>
        <permalink>xlarge-notebook</permalink>
        <url>/collection/xlarge-notebook</url>
    </collection>
</collections>

Получение информации о категории
GET /admin/collections/7830.xml
< 200
< Content-Type: application/xml
<collection>
    <id type="integer">7830</id>
    <is-hidden type="boolean">false</is-hidden>
    <parent-id type="integer">2628</parent-id>
    <to-torg-mail type="boolean" nil="true"></to-torg-mail>
    <to-yandex-market type="boolean">true</to-yandex-market>
    <title>Moleskine XLarge 19х25</title>
    <description nil="true"></description>
    <html-title nil="true"></html-title>
    <meta-description nil="true"></meta-description>
    <meta-keywords nil="true"></meta-keywords>
    <permalink>xlarge-notebook</permalink>
    <url>/collection/xlarge-notebook</url>
</collection>

Добавление новой категории
POST /admin/collections.xml
> Content-Type: application/xml
<collection>
    <parent-id type="integer">2628</parent-id>
    <title>Moleskine XLarge 19х25</title>
</collection>
< 200
< Content-Type: application/xml
<collection>
    <id type="integer">7830</id>
    <is-hidden type="boolean">false</is-hidden>
    <parent-id type="integer">2628</parent-id>
    <to-torg-mail type="boolean" nil="true"></to-torg-mail>
    <to-yandex-market type="boolean" nil="true"></to-yandex-market>
    <title>Moleskine XLarge 19х25</title>
    <description nil="true"></description>
    <html-title nil="true"></html-title>
    <meta-description nil="true"></meta-description>
    <meta-keywords nil="true"></meta-keywords>
    <permalink>xlarge-notebook</permalink>
    <url>/collection/xlarge-notebook</url>
</collection>

Редактирование категории
PUT /admin/collections/7830.xml
> Content-Type: application/xml
<collection>
    <is-hidden type="boolean">true</is-hidden>
</collection>
< 200
< Content-Type: application/xml
<collection>
    <id type="integer">7830</id>
    <is-hidden type="boolean">true</is-hidden>
    <parent-id type="integer">2628</parent-id>
    <to-torg-mail type="boolean" nil="true"></to-torg-mail>
    <to-yandex-market type="boolean" nil="true"></to-yandex-market>
    <title>Moleskine XLarge 19х25</title>
    <description nil="true"></description>
    <html-title nil="true"></html-title>
    <meta-description nil="true"></meta-description>
    <meta-keywords nil="true"></meta-keywords>
    <permalink>xlarge-notebook</permalink>
    <url>/collection/xlarge-notebook</url>
    <sort-type type="integer">3</sort-type>
</collection>

Удаление категории
DELETE /admin/collections/7830.xml
< 200

