HOST: http://insales.ru/

--- insales.ru test API ---

--
Категории на складе
--
Получение списка категорий
GET /admin/categories.xml
< 200
< Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<categories type="array">
    <category>
        <id type="integer">28429</id>
        <parent-id type="integer" nil="true"/>
        <title>Склад</title>
        <position type="integer">1</position>
        <created-at type="timestamp">2009-10-22 19:41:19 +0400</created-at>
        <updated-at type="timestamp">2009-11-05 15:00:11 +0300</updated-at>
    </category>
    <category>
        <id type="integer">32142</id>
        <parent-id type="integer">28429</parent-id>
        <title>Мужская одежда</title>
        <position type="integer">2</position>
        <created-at type="timestamp">2009-11-19 14:06:31 +0300</created-at>
        <updated-at type="timestamp">2009-11-19 14:06:36 +0300</updated-at>
    </category>
    <category>
        <id type="integer">28479</id>
        <parent-id type="integer">28429</parent-id>
        <title>Женская одежда</title>
        <position type="integer">1</position>
        <created-at type="timestamp">2009-10-23 19:47:24 +0400</created-at>
        <updated-at type="timestamp">2009-10-23 19:47:24 +0400</updated-at>
    </category>
    <category>
        <id type="integer">28480</id>
        <parent-id type="integer">28429</parent-id>
        <title>Платья</title>
        <position type="integer">1</position>
        <created-at type="timestamp">2009-10-23 19:47:24 +0400</created-at>
        <updated-at type="timestamp">2009-10-23 19:47:24 +0400</updated-at>
   </category>
</categories>

Получение информации о категории
GET /admin/categories/32142.xml
< 200
< Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<category>
    <id type="integer">32142</id>
    <parent-id type="integer">28429</parent-id>
    <title>Мужская одежда</title>
    <position type="integer">2</position>
    <created-at type="timestamp">2009-11-19 14:06:31 +0300</created-at>
    <updated-at type="timestamp">2009-11-19 14:06:36 +0300</updated-at>
</category>

Добавление новой категории
POST /admin/categories.xml
> Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<category>
    <parent-id type="integer">28429</parent-id>
    <title>Мужская одежда</title>
</category>
< 200
< Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<category>
    <id type="integer">32142</id>
    <parent-id type="integer">28429</parent-id>
    <title>Мужская одежда</title>
    <position type="integer">2</position>
    <created-at type="timestamp">2009-11-19 14:06:31 +0300</created-at>
    <updated-at type="timestamp">2009-11-19 14:06:36 +0300</updated-at>
</category>

Редактирование категории
PUT /admin/categories/32142.xml
> Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<category>
    <id type="integer">32142</id>
    <title>Одежда</title>
</category>
< 200
< Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?>
<category>
    <id type="integer">32142</id>
    <parent-id type="integer">28429</parent-id>
    <title>Одежда</title>
    <position type="integer">2</position>
    <created-at type="timestamp">2009-11-19 14:06:31 +0300</created-at>
    <updated-at type="timestamp">2009-11-19 14:06:36 +0300</updated-at>
</category>

Удаление категории
DELETE /admin/categories/32142.xml
< 200